# run redis in docker

version: '3.7'

services:
  redis:
    image: redis:6.2.5
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    command: redis-server --appendonly yes
